packages:
  - "packages/*"
  - "apps/*"
  - tooling/*
  - "!**/test/**"

catalog:
  "typescript": "^5.6.2"
  prettier: ^3.4.1
  "prettier-plugin-tailwindcss": "^0.6.9"
  "eslint": "^9.15.0"
  "@types/eslint": "^8.56.10"
  "typescript-eslint": "^8.15.0"
  "@types/eslint__js": "8.42.3"
  "@typescript-eslint/eslint-plugin": "^8.1.0"
  "@typescript-eslint/parser": "^8.1.0"
  "@t3-oss/env-nextjs": "^0.10.1"
  "superjson": "^2.2.1"
  "zod": "^3.23.3"
  "@tanstack/react-query": "^5.50.0"
  "dotenv": "^16.4.5"
  "dotenv-cli": "^7.4.4"
catalogs:
  node20:
    "@types/node": "^20.14.10"
  react18:
    "react": "^18.3.1"
    "react-dom": "^18.3.1"
    "@types/react-dom": "^18.3.1"
    "@types/react": "^18.3.3"
  next15:
    "next": "^15.0.1"
    "next-auth": "5.0.0-beta.25"
    "@auth/core": "0.37.2"
    "@auth/prisma-adapter": "^2.7.2"
    "eslint-config-next": "^15.0.1"
    "server-only": "^0.0.1"
    "geist": "^1.3.0"
  tailwindcss:
    "tailwindcss": "^3.4.15"
    "tailwindcss-animate": "^1.0.7"
    "@tailwindcss/typography": "^0.5.15"
    "postcss": "^8.4.39"
    "tailwind-merge": "^2.5.5"
  storybook:
    "storybook": "^8.4.6"
    "@storybook/addon-docs": "^8.4.6"
    "@storybook/addon-essentials": "^8.4.6"
    "@storybook/addon-interactions": "^8.4.6"
    "@storybook/addon-onboarding": "^8.4.6"
    "@storybook/blocks": "^8.4.6"
    "@storybook/experimental-nextjs-vite": "^8.4.6"
    "@storybook/react": "^8.4.6"
    "@storybook/react-vite": "^8.4.6"
    "@storybook/test": "^8.4.6"
    "@storybook/test-runner": "^0.20.1"
  prisma5:
    "prisma": "^5.14.0"
    "@prisma/client": "^5.14.0"
    "@auth/prisma-adapter": "^2.7.2"
  trpc11:
    "@trpc/client": "^11.0.0-rc.446"
    "@trpc/react-query": "^11.0.0-rc.446"
    "@trpc/server": "^11.0.0-rc.446"
  storyblok:
    "@storyblok/react": "4"
