import "../styles/globals.css";

import { type Metadata } from "next";
import { GeistSans } from "geist/font/sans";

import { CounterStoreProvider } from "~/stores/counter-store-provider";
import { TRPCReactProvider } from "../trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  appleWebApp: {
    title: "Create T3 App",
    statusBarStyle: "default",
    startupImage: "/apple-touch-icon.png",
  },
  icons: [
    {
      rel: "icon",
      url: "/favicon.ico",
    },
    {
      rel: "icon",
      url: "/favicon.ico",
      sizes: "any",
    },
    {
      rel: "icon",
      url: "/favicon.svg",
      sizes: "any",
      type: "image/svg+xml",
    },
    {
      rel: "apple-touch-icon",
      url: "/apple-touch-icon.png",
      sizes: "any",
      type: "image/svg+xml",
    },
  ],
};

// For viewport configuration, create a separate export
export const viewport = {
  themeColor: "#2563EB",
  colorScheme: "light",
  viewportFit: "cover",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <CounterStoreProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </CounterStoreProvider>
      </body>
    </html>
  );
}
