// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface FeatureStoryblok {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: any;
}

export interface GridStoryblok {
  columns?: (
    | FeatureStoryblok
    | GridStoryblok
    | HeroBannerStoryblok
    | PageStoryblok
    | TabPanelStoryblok
    | TabsPanelStoryblok
    | TeaserStoryblok
  )[];
  component: "grid";
  _uid: string;
  [k: string]: any;
}

export type MultiassetStoryblok = {
  alt: string | null;
  copyright?: string | null;
  fieldtype: "asset";
  id: number;
  filename: string | null;
  name: string;
  title: string | null;
  focus: string | null;
  meta_data?: {
    [k: string]: any;
  };
  source?: string | null;
  is_external_url?: boolean;
  is_private?: boolean;
  src?: string;
  updated_at?: string;
  width?: number | null;
  height?: number | null;
  aspect_ratio?: number | null;
  public_id?: string | null;
  content_type?: string;
  [k: string]: any;
}[];

export interface HeroBannerStoryblok {
  title?: string;
  description?: string;
  images?: MultiassetStoryblok;
  component: "heroBanner";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  title?: string;
  description?: string;
  body?: (
    | FeatureStoryblok
    | GridStoryblok
    | HeroBannerStoryblok
    | PageStoryblok
    | TabPanelStoryblok
    | TabsPanelStoryblok
    | TeaserStoryblok
  )[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface TabPanelStoryblok {
  tabLabel?: string;
  tabBody?: (
    | FeatureStoryblok
    | GridStoryblok
    | HeroBannerStoryblok
    | PageStoryblok
    | TabPanelStoryblok
    | TabsPanelStoryblok
    | TeaserStoryblok
  )[];
  component: "tabPanel";
  _uid: string;
  [k: string]: any;
}

export interface TabsPanelStoryblok {
  title?: string;
  tabs?: TabPanelStoryblok[];
  component: "tabsPanel";
  _uid: string;
  [k: string]: any;
}

export interface TeaserStoryblok {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: any;
}
