name: "Chromatic"

on: push

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install turborepo
        run: pnpm add -g @turborepo/cli
      - name: Install dependencies
        run: pnpm install
      - name: Run Chromatic
        uses: chromaui/action@latest

        # change the directory to the storybook app
        with:
          command: "turborepo run storybook:chromatic -- --project-token=$CHROMATIC_PROJECT_TOKEN"
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
